version: '3'
services:
  fuseki:
    image: linkedsolutions/fuseki-oidc 
    depends_on:
      - "keycloak"
    ports:
      - "3030:3030"
      - "15005:15005" # Debugging
    volumes:
      - ./db:/db
    environment:
      AUTH_SERVER_URL: "http://keycloak:8080/auth"
  keycloak:
    image: "jboss/keycloak"
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
    ports:
      - "8080:8080"
  sample:
    image: "linkedsolutions/fuseki-oidc-sample-client"
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
    ports:
      - "8081:8080"